name: build-on-push

on: 
 push: 
   branches: 
     - develop 
 workflow_dispatch :

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Tagging
        run: | 
          echo "Testing"  
 
