name: build-on-pre-release

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest 
    

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3 

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker  us-central1-docker.pkg.dev

      - name: Tagging
        run: |
          
          TAG_NAME=${{ github.event.release.tag_name }} 
          echo "${TAG_NAME}" 
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV 

      - name: Build Docker Image
        run: |
          IMAGE_NAME="docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pyappapi/pyappapi"
          docker build -t ${IMAGE_NAME}:${{ env.TAG_NAME }} . 
      
      - name: Push Docker Image to GCR
        run: | 
          IMAGE_NAME="docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pyappapi/pyappapi"
          docker push ${IMAGE_NAME}:${{ env.TAG_NAME }}
          