name: build-on-pre-release

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest 
    

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3 

      - name: Tagging
        run: |
          TAG_NAME=${{ github.event.release.tag_name }} 
          echo "${TAG_NAME}"  

      - name: Build Docker Image
        run: |
          docker build -t pyappapi:${{ env.TAG_NAME }} . 
          