name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: "ImagetTag"
        required: true
        type: string
        default: pyappapi:v1.0.33
      RUN_ENVIRONMENT:
        description: "Env to Run"
        required: true
        type: choice
        options:
          - dev
          - staging
          - production 
        default: dev

  repository_dispatch:
    types:
      - deploy

env:
  NAME_SPACE: myapp-k8s-dev

jobs:

  deploy:
    runs-on: ubuntu-latest 
    steps:
    # Check out the repository
    - name: Check Out Code
      uses: actions/checkout@v3 
      
    - name: Deploy to Kubernetes Cluster
      run: |    
        export NAME_SPACE=${{ env.NAME_SPACE }}
        export IMAGE_NAME=${{ inputs.IMAGE_NAME }}
        export My_ENV=${{ inputs.RUN_ENVIRONMENT }}
        #envsubst < deployment.yaml > updated-deployment.yaml
        #envsubst < service.yaml > updated-service.yaml
        #kubectl apply -f updated-deployment.yaml
        #kubectl apply -f updated-service.yaml
        echo "{{ $NAME_SPACE }}"
        echo "{{ $NAME_SPACE }}"
        echo "{{ $IMAGE_NAME }}"
         