name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Image to Deploy"
        required: true
        type: string


jobs:

  deploy:
    runs-on: ubuntu-latest 
    steps:
    # Check out the repository
    - name: Check Out Code
      uses: actions/checkout@v3
    - name: Set Up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_KEY }} 
    
    - name: Configure gcloud CLI
      run: |   
        gcloud config set compute/zone us-central1-c
        gcloud container clusters get-credentials myk8-cluster
        kubectl get ns
         