name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: "Image to Deploy"
        required: true
        type: string

env:
  NAME_SPACE: myapp-k8s-dev

jobs:

  deploy:
    runs-on: ubuntu-latest 
    steps:
    # Check out the repository
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_KEY }} 

    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: myk8-cluster
        location: us-central1-c 
 
    
    - name: Deploy to Kubernetes Cluster
      run: |    
        export NAME_SPACE=${{ env.NAME_SPACE }}
        export IMAGE_NAME=${{ inputs.IMAGE_NAME }}
        envsubst < deployment.yaml > updated-deployment.yaml
        envsubst < service.yaml > updated-service.yaml
        kubectl apply -f updated-deployment.yaml
        kubectl apply -f updated-service.yaml
         